version: '3' 

services: 
  backend:  
    image: myback
    build: backendopt/.
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/app/backend/logs.txt
    container_name: back

  frontend:  
    image: myfront
    build: frontendopt/.
    ports:
      - 5000:5000
    container_name: front
