version: '3' 

services: 
  backend:  
    image: myback:alpine
    build:
      context: ./backendopt
      dockerfile: Dockerfile.alpine
    ports:
      - 8000:8000
    volumes:
      - ./logs.txt:/app/backend/logs.txt
    container_name: back

  frontend:  
    image: myfront:alpine
    build:
      context: ./frontendopt
      dockerfile: Dockerfile.alpine
    ports:
      - 5000:5000
    container_name: front
