version: '3.5' 

services: 
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    container_name: web
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

  backend:
    image: myback
    build: backend/.
    volumes:
      - ./logs.txt:/app/backend/logs.txt
    container_name: back
    environment:
      - FRONT_URL=http://localhost/
      - REDIS=myredis
      - DB_USERNAME=backend
      - DB_PASSWORD=Secret292
      - DB_HOST=db
    depends_on:
      - myredis
      - db

  frontend:  
    image: myfront
    build: frontend/.
    container_name: front
    environment:
      - API_URL=http://localhost/api
    depends_on:
      - backend

  myredis:
    image: redis
    volumes:
      - ./redisdata:/data
    container_name: redis

  db:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=backend
      - POSTGRES_PASSWORD=Secret292
